apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: 'mongodb+srv://rohanxobruno:jqqIKyzeqoizwHGn@cluster0.wfyg8vn.mongodb.net/books-collection?retryWrites=true&w=majority'